import { randomUUID } from 'node:crypto';
import { Context, Service } from '@deepseek-ai/cordis';
import type { KvTable } from '@deepseek-ai/dsh-storage-domain';
import type { ActorContext } from 'workdsh-contracts';
import type { CreateProjectInput, Project, ProjectActivity, ProjectAssetRef, ProjectCapabilityRef, ProjectConfig, ProjectConfigRevision, ProjectInputRef, ProjectService, ProjectSnapshot, ProjectTaskContext, ProjectTaskLink, ProjectTemplate, ProjectWorkItem } from 'workdsh-contracts/projects';
import { PROJECT_INSTRUCTION_TOKEN_BUDGET, estimateProjectInstructionTokens } from '../instruction-budget.js';
import { projectDomainSpec, projectStateKey, type ProjectState } from '../storage/domain.js';
declare module '@deepseek-ai/cordis' { interface Context { workdshProjects: ProjectService; } }
const timestamp = () => new Date().toISOString();
const clean = (value: string, code = 'projects/invalid-name', max = 10_000) => { const next = value.trim(); if (!next || next.length > max) throw new Error(code); return next; };
const templates: readonly ProjectTemplate[] = [
  { id: 'product', name: '产品需求全流程', description: '从需求规划、PRD 到研发测试验收', instruction: '围绕产品目标维护需求、计划、任务、资产和决策记录。' },
  { id: 'research', name: '市场调研与竞品分析', description: '深度调研、竞品拆解、报告评审', instruction: '引用可核验资料，区分事实、推断与建议，持续沉淀研究资产。' },
  { id: 'knowledge', name: '团队知识库', description: '持续沉淀 SOP、经验和 FAQ', instruction: '优先复用项目资产，输出可维护、可追溯的团队知识。' },
  { id: 'delivery', name: '项目交付', description: '管理客户需求、计划、风险和周报', instruction: '跟踪交付范围、负责人、时间、风险和验收证据。' },
  { id: 'bugs', name: 'Bug 跟踪/测试验收', description: '持续跟踪 Bug、测试用例和验收', instruction: '问题必须关联复现步骤、负责人、优先级、状态和验证证据。' },
  // 融媒体模板矩阵：新闻稿件类
  { id: 'media-cctv', name: '央视新闻稿', description: '电视新闻与口播稿，主题主线突出、播报文风', instruction: '本项目生产符合中央广播电视总台新闻节目风格的稿件。要求：1）坚持正确导向，时政表述以权威通稿为准，规范使用专有名词与职务称谓；2）文风口语化、短句为主，适合播报节奏，避免书面长句和生僻词；3）导语点明核心事实，正文按重要程度递进，段落间有明确逻辑提示；4）政策、数据、引语必须注明权威信源，未经核实的信息一律标注存疑；5）成稿后逐条核对禁用词与安全播出要求，敏感议题先提请项目负责人确认。默认输出口播稿与文字稿两个版本。', capabilities: [{ kind: 'expert', id: 'media-cctv-writer', label: '央视时政新闻写作专家' }, { kind: 'skill', id: 'workdsh-news-cctv', label: '央视新闻稿写作' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }, { kind: 'skill', id: 'workdsh-publish-compliance', label: '发布前合规审核' }], workItems: [{ title: '选题立项', priority: 'medium', tags: ['稿件工作流'] }, { title: '信源核实与采访', priority: 'high', tags: ['稿件工作流'] }, { title: '初稿撰写', priority: 'high', tags: ['稿件工作流'] }, { title: '三审三校', priority: 'high', tags: ['稿件工作流'] }, { title: '签发与发布', priority: 'medium', tags: ['稿件工作流'] }] },
  { id: 'media-xinhua', name: '新华社新闻稿', description: '消息通稿，倒金字塔结构与电头信源规范', instruction: '本项目生产符合新华社消息体例的通稿。要求：1）使用规范消息头（电头）与导语，倒金字塔结构，最重要事实前置；2）一条消息一个主题：快讯百字以内，消息 500 字左右，综述另行约定；3）信源必须权威可核验，直接引语忠于原话，匿名信源须说明理由并经项目负责人确认；4）人名、职务、机构名、政策文号逐一核对，数字与计量单位符合规范；5）成稿后自查新闻五要素（时间、地点、人物、事件、原因）齐备，缺失要素显式标注。', capabilities: [{ kind: 'expert', id: 'media-xinhua-writer', label: '新华社通稿写作专家' }, { kind: 'skill', id: 'workdsh-news-xinhua', label: '新华社新闻稿写作' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }, { kind: 'skill', id: 'workdsh-publish-compliance', label: '发布前合规审核' }], workItems: [{ title: '选题立项', priority: 'medium', tags: ['稿件工作流'] }, { title: '信源核实与采访', priority: 'high', tags: ['稿件工作流'] }, { title: '初稿撰写', priority: 'high', tags: ['稿件工作流'] }, { title: '三审三校', priority: 'high', tags: ['稿件工作流'] }, { title: '签发与发布', priority: 'medium', tags: ['稿件工作流'] }] },
  { id: 'media-renmin', name: '人民日报新闻稿', description: '要闻与评论文章，政论结构与政策表述规范', instruction: '本项目生产符合人民日报要闻版与评论版风格的稿件。要求：1）要闻稿坚持导向正确、事实准确，政策表述以官方发布为准，不引申不演绎；2）评论文章立意从政策与全局出发，论点、论据、论证层次分明，标题观点鲜明；3）用词庄重规范，避免网络用语和夸张修辞，成语典故引用准确；4）引文注明出处，重要论述引用以权威文本为准；5）成稿后核对提法与现行表述的一致性，发现过时提法立即标记更正。', capabilities: [{ kind: 'expert', id: 'media-renmin-writer', label: '人民日报报道与评论专家' }, { kind: 'skill', id: 'workdsh-news-renmin', label: '人民日报新闻稿写作' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }, { kind: 'skill', id: 'workdsh-publish-compliance', label: '发布前合规审核' }], workItems: [{ title: '选题立项', priority: 'medium', tags: ['稿件工作流'] }, { title: '信源核实与采访', priority: 'high', tags: ['稿件工作流'] }, { title: '初稿撰写', priority: 'high', tags: ['稿件工作流'] }, { title: '三审三校', priority: 'high', tags: ['稿件工作流'] }, { title: '签发与发布', priority: 'medium', tags: ['稿件工作流'] }] },
  { id: 'media-industry-energy', name: '能源行业新闻稿', description: '能源媒体口径，数据带出处、产业链术语规范', instruction: '本项目生产面向能源行业的新闻稿（电力、新能源、储能、油气、双碳等）。要求：1）专业口径准确：装机容量区分 GW/MW，发电量区分亿千瓦时，电价、利用率、消纳率等指标注明口径与统计范围；2）数据必须带出处（企业公告、统计部门、能源主管部门发布），没有出处的数据不得使用；3）政策引用到文号与发布日期，概括不得失真；4）产业链表述规范：项目名称、业主方、设备方、EPC 方角色关系不得混淆；5）投资额与收益测算保持谨慎，区分企业披露与记者测算；6）成稿后对照能源行业术语表核查常见误用。', capabilities: [{ kind: 'expert', id: 'media-energy-correspondent', label: '能源行业新闻采写专家' }, { kind: 'skill', id: 'workdsh-news-industry-energy', label: '能源行业新闻稿写作' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }, { kind: 'skill', id: 'workdsh-publish-compliance', label: '发布前合规审核' }], workItems: [{ title: '选题立项', priority: 'medium', tags: ['稿件工作流'] }, { title: '信源核实与采访', priority: 'high', tags: ['稿件工作流'] }, { title: '初稿撰写', priority: 'high', tags: ['稿件工作流'] }, { title: '三审三校', priority: 'high', tags: ['稿件工作流'] }, { title: '发布前合规审核', priority: 'high', tags: ['稿件工作流'] }, { title: '签发与发布', priority: 'medium', tags: ['稿件工作流'] }] },
  // 融媒体模板矩阵：内容生产类（国央企融媒体场景：选题发现、稿件、图片、视频）
  { id: 'media-briefing', name: '企业动态简报', description: '固定栏目要闻与动态汇编（早报/晚报）', instruction: '本项目生产固定栏目企业动态简报（早报/晚报）。要求：1）栏目结构与版式稳定，条目按既定栏目归位（要闻动态、行业政策、基层一线等）；2）每条注明来源与时间，转载内容注明原始出处；3）多条信源交叉核实，无法核实的传闻不得收录或明确标注；4）表述符合宣传口径，涉及领导活动与企业数据的表述严格按审定稿；5）摘要精炼，每条不超过既定字数，不做标题党。', capabilities: [{ kind: 'expert', id: 'media-energy-correspondent', label: '能源行业新闻采写专家' }, { kind: 'expert', id: 'media-desk-editor', label: '融媒体审校签发专家' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }], workItems: [{ title: '信息收集与筛选', priority: 'medium', tags: ['栏目生产'] }, { title: '交叉核实信源', priority: 'high', tags: ['栏目生产'] }, { title: '按栏目模板汇编', priority: 'medium', tags: ['栏目生产'] }, { title: '审校', priority: 'high', tags: ['栏目生产'] }, { title: '定时发布', priority: 'medium', tags: ['栏目生产'] }] },
  { id: 'media-image-production', name: '图片生产', description: '宣传图片与海报，VI 规范与合规审查', instruction: '本项目生产宣传图片与海报（活动配图、主题海报、图解）。要求：1）先确认用途、发布渠道与宣传口径，再进入创作；2）构图与文案符合企业视觉识别（VI）规范，领导同志肖像、职务、排序严格按审定版本；3）涉及地图的画面必须使用标准地图（自然资源部标准地图服务），国界省界不得变形；4）国旗、国徽、党旗等符号使用符合法律法规；5）AI 生成或后期处理的图像须可追溯说明，新闻纪实场景不得虚构合成；6）成图后对照合规清单逐项审查再交付。', capabilities: [{ kind: 'expert', id: 'media-visual-producer', label: '图片生产专家' }, { kind: 'skill', id: 'workdsh-visual-production', label: '视觉内容生产' }, { kind: 'skill', id: 'workdsh-publish-compliance', label: '发布前合规审核' }], workItems: [{ title: '需求与口径确认', priority: 'medium', tags: ['图片生产'] }, { title: '创意与构图方案', priority: 'medium', tags: ['图片生产'] }, { title: '素材生产', priority: 'high', tags: ['图片生产'] }, { title: '合规审校（标识·地图·肖像）', priority: 'high', tags: ['图片生产'] }, { title: '交付归档', priority: 'low', tags: ['图片生产'] }] },
  { id: 'media-video-script', name: '视频脚本生产', description: '宣传片、新闻短视频与微记录脚本', instruction: '本项目生产视频脚本（宣传片、新闻短视频、微记录）。要求：1）明确视频类型、目标平台与时长目标后再动笔；2）脚本使用分镜表：镜号、画面内容、口播/字幕、时长、素材来源；3）口播稿符合播报规范，短句口语化，字幕与口播一致；4）重大主题脚本先按报备流程审校再制作；5）音乐、字体、素材版权逐一确认，不留未授权素材；6）脚本交付同时给出拍摄清单或素材剪辑需求清单。', capabilities: [{ kind: 'expert', id: 'media-video-scriptwriter', label: '视频脚本创作专家' }, { kind: 'skill', id: 'workdsh-video-script', label: '视频脚本生产' }, { kind: 'skill', id: 'workdsh-publish-compliance', label: '发布前合规审核' }], workItems: [{ title: '主题与口径确认', priority: 'medium', tags: ['视频脚本'] }, { title: '脚本结构设计', priority: 'medium', tags: ['视频脚本'] }, { title: '分镜脚本撰写', priority: 'high', tags: ['视频脚本'] }, { title: '合规审校', priority: 'high', tags: ['视频脚本'] }, { title: '交付归档', priority: 'low', tags: ['视频脚本'] }] },
  { id: 'media-video-analysis', name: '视频资源分析', description: '素材库盘点、可用性标注与补拍建议', instruction: '本项目对视频素材资源做分析盘点。要求：1）盘点素材建立清单：标题、时长、格式、拍摄时间、内容主题；2）按主题与可用性标注，可复用片段记到时间码；3）识别内容质量与合规风险（过期表述、不当画面、授权到期）；4）输出分析报告：素材结构、缺口、复用与补拍建议；5）结论以实际提供的素材为据，不臆测未提供的内容。', capabilities: [{ kind: 'expert', id: 'media-video-scriptwriter', label: '视频脚本创作专家' }, { kind: 'skill', id: 'workdsh-video-script', label: '视频脚本生产' }], workItems: [{ title: '素材清单盘点', priority: 'medium', tags: ['视频分析'] }, { title: '内容分析标注', priority: 'high', tags: ['视频分析'] }, { title: '可用性评估', priority: 'high', tags: ['视频分析'] }, { title: '分析报告归档', priority: 'low', tags: ['视频分析'] }] },
  // 融媒体模板矩阵：深度与访谈类
  { id: 'media-feature-deep', name: '深度报道/专题', description: '长周期调研型深度稿件', instruction: '本项目生产深度报道与专题。要求：1）选题立项时写明核心问题、目标读者与预期证据链；2）多方信源平衡，利益相关方必须获得回应机会；3）采访时速记整理归档到项目资产，引用可回溯；4）数据可视化需求单独列任务；5）成稿前逐条核对事实与引语，长稿按章节核对；6）发布后跟踪反馈，沉淀复盘到活动记录。', capabilities: [{ kind: 'expert', id: 'media-energy-correspondent', label: '能源行业新闻采写专家' }, { kind: 'expert', id: 'media-topic-planner', label: '选题发现与策划专家' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }], workItems: [{ title: '选题评估', priority: 'medium', tags: ['深度报道'] }, { title: '调研与采访', priority: 'high', tags: ['深度报道'] }, { title: '初稿撰写', priority: 'high', tags: ['深度报道'] }, { title: '信源复核与专家审阅', priority: 'high', tags: ['深度报道'] }, { title: '修订定稿', priority: 'medium', tags: ['深度报道'] }, { title: '发布与传播跟踪', priority: 'low', tags: ['深度报道'] }] },
  { id: 'media-roundtable', name: '圆桌访谈/对话', description: '嘉宾对话栏目全流程', instruction: '本项目组织圆桌访谈或对话栏目。要求：1）议题聚焦，提纲问题按递进设计，敏感问题准备追问与替代问法；2）嘉宾背景与职务逐一核实；3）访谈记录完整归档，整理稿忠于原意，删改处保持上下文完整；4）多人观点呈现平衡，不同立场并列不剪裁；5）整理稿经嘉宾确认后再发布，未确认观点不署名引用。', capabilities: [{ kind: 'expert', id: 'media-topic-planner', label: '选题发现与策划专家' }, { kind: 'expert', id: 'media-desk-editor', label: '融媒体审校签发专家' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }], workItems: [{ title: '议题与嘉宾确认', priority: 'medium', tags: ['访谈'] }, { title: '提纲设计', priority: 'high', tags: ['访谈'] }, { title: '访谈执行', priority: 'high', tags: ['访谈'] }, { title: '内容整理成稿', priority: 'high', tags: ['访谈'] }, { title: '审校与发布', priority: 'medium', tags: ['访谈'] }] },
  // 融媒体模板矩阵：运营与分发类
  { id: 'media-hotspot', name: '热点监测与快速响应', description: '行业热点捕捉、核查与快速成稿', instruction: '本项目负责行业热点监测与快速响应。要求：1）先研判再动手：确认热点真实性、相关性与时效窗口；2）快稿以已核实事实为界，未确认部分明确标注「截至发稿」；3）持续滚动更新，修正处显式标记，不静默改写；4）跟进深度稿与快稿分开管理；5）全程保留信源清单到项目资产。', capabilities: [{ kind: 'expert', id: 'media-topic-planner', label: '选题发现与策划专家' }, { kind: 'expert', id: 'media-desk-editor', label: '融媒体审校签发专家' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }], workItems: [{ title: '热点捕捉与研判', priority: 'high', tags: ['热点响应'] }, { title: '事实核查', priority: 'high', tags: ['热点响应'] }, { title: '快稿撰写', priority: 'high', tags: ['热点响应'] }, { title: '快速审校', priority: 'high', tags: ['热点响应'] }, { title: '发布', priority: 'medium', tags: ['热点响应'] }, { title: '后续跟进', priority: 'low', tags: ['热点响应'] }] },
  { id: 'media-rewrite', name: '多平台改写分发', description: '一稿多发，按平台属性适配改写', instruction: '本项目将原稿改写适配至多平台。要求：1）先确认原稿版权与可改写范围；2）按平台属性改写：公众号保留深度与排版层次，短视频脚本转为口语化分镜描述，微博/快讯压缩到平台字数内保留核心事实；3）改写不改变事实与结论，观点强度不升级；4）各平台发布时间与合规要求单独核对；5）记录各平台链接与数据反馈到项目资产。', capabilities: [{ kind: 'expert', id: 'media-distribution-editor', label: '多平台分发专家' }, { kind: 'skill', id: 'workdsh-platform-rewrite', label: '多平台改写' }, { kind: 'skill', id: 'workdsh-news-desk', label: '新闻审校台' }, { kind: 'skill', id: 'workdsh-publish-compliance', label: '发布前合规审核' }], workItems: [{ title: '锁定原稿与版权确认', priority: 'medium', tags: ['分发'] }, { title: '平台适配改写', priority: 'high', tags: ['分发'] }, { title: '各平台审校', priority: 'high', tags: ['分发'] }, { title: '分发与效果记录', priority: 'low', tags: ['分发'] }] },
  { id: 'media-topic-planning', name: '选题发现与策划', description: '选题发现、评估与排期', instruction: '本项目维护选题库与排期，负责选题发现。要求：1）选题发现渠道固定跟踪：上级精神与政策发布、行业动态、企业中心工作、重要时间节点、舆情热点；2）选题条目包含核心问题、目标读者、预期体裁、信源线索与时效窗口；3）评估维度固定：导向安全、新闻价值、专业价值、可操作性；4）重大选题按报备流程处理后再排期；5）明确区分「已立项」「储备」「搁置」，搁置注明原因；6）立项后转入对应稿件项目执行。', capabilities: [{ kind: 'expert', id: 'media-topic-planner', label: '选题发现与策划专家' }, { kind: 'skill', id: 'workdsh-topic-discovery', label: '选题发现与策划' }], workItems: [{ title: '选题发现与征集', priority: 'medium', tags: ['选题'] }, { title: '价值评估', priority: 'medium', tags: ['选题'] }, { title: '立项与排期', priority: 'low', tags: ['选题'] }, { title: '跟踪执行', priority: 'low', tags: ['选题'] }] },
  // 融媒体模板矩阵：复盘管理类
  { id: 'media-review-retro', name: '内容运营复盘', description: '数据回顾、归因分析与策略调整', instruction: '本项目做内容运营复盘。要求：1）数据取自各平台真实后台，截图或导出文件归档到项目资产；2）归因区分内容因素与渠道因素，不把波动全归因于单一变量；3）结论必须落到可执行策略，明确负责人与检验指标；4）与历史复盘对比，标注策略有效性。', capabilities: [{ kind: 'expert', id: 'media-desk-editor', label: '融媒体审校签发专家' }, { kind: 'expert', id: 'media-distribution-editor', label: '多平台分发专家' }], workItems: [{ title: '数据汇总', priority: 'medium', tags: ['复盘'] }, { title: '归因分析', priority: 'high', tags: ['复盘'] }, { title: '结论与策略调整', priority: 'high', tags: ['复盘'] }, { title: '归档', priority: 'low', tags: ['复盘'] }] },
];
// 模板分类：驱动项目中心分类筛选与图标着色（UI 侧 TPL_CATEGORY_META 同名字典对应）。
const templateCategories: Record<string, string> = {
  product: '通用协作', research: '通用协作', knowledge: '通用协作', delivery: '通用协作', bugs: '通用协作',
  'media-cctv': '新闻稿件', 'media-xinhua': '新闻稿件', 'media-renmin': '新闻稿件', 'media-industry-energy': '新闻稿件',
  'media-briefing': '内容生产', 'media-image-production': '内容生产', 'media-video-script': '内容生产', 'media-video-analysis': '内容生产',
  'media-feature-deep': '深度访谈', 'media-roundtable': '深度访谈',
  'media-topic-planning': '运营管理', 'media-hotspot': '运营管理',
  'media-rewrite': '分发复盘', 'media-review-retro': '分发复盘',
};
const allTemplates: readonly ProjectTemplate[] = templates.map(row => ({ ...row, category: templateCategories[row.id] ?? '通用协作' }));
type Stored = ProjectState & { projects: Record<string, Project>; configs: Record<string, ProjectConfigRevision>; workItems: Record<string, ProjectWorkItem>; assets: Record<string, ProjectAssetRef>; tasks: Record<string, ProjectTaskLink>; activity: Record<string, ProjectActivity> };
export class ProjectManager extends Service implements ProjectService {
  static inject = ['storageDomain']; private table?: KvTable<string, ProjectState>; private serial: Promise<unknown> = Promise.resolve();
  constructor(ctx: Context) { super(ctx, 'workdshProjects'); }
  async [Service.init]() { const domain = await this.ctx.storageDomain.open(projectDomainSpec); this.table = domain.table('states'); this.ctx.effect(() => () => domain.close(), 'workdshProjects.domainClose'); }
  templates() { return Promise.resolve(allTemplates); }
  list(actor: ActorContext, query = '') { return this.listForStatus(actor,query,'active'); }
  listArchived(actor: ActorContext, query = '') { return this.listForStatus(actor,query,'archived'); }
  create(actor: ActorContext, input: CreateProjectInput) { return this.enqueue(async () => { const state = await this.state(actor); const template = input.templateId ? allTemplates.find(row => row.id === input.templateId) : undefined; if (input.templateId && !template) throw new Error('projects/template-not-found'); const now = timestamp(), projectId = randomUUID(), configId = randomUUID(); const project: Project = { id: projectId, name: clean(input.name), description: input.description?.trim() || template?.description || '', ...(template ? { templateId: template.id } : {}), owner: { organizationId: actor.organizationId, ownerPrincipalId: actor.principalId, scope: 'personal' }, status: 'active', configRevisionId: configId, createdAt: now, updatedAt: now }; const config: ProjectConfigRevision = { id: configId, projectId, number: 1, instruction: template?.instruction ?? '', capabilities: (template?.capabilities ?? []).map(row => ({ kind: row.kind, id: row.id, label: row.label })), createdBy: actor.principalId, createdAt: now }; const templateItems = (template?.workItems ?? []).map(row => { const id = randomUUID(); return { id, projectId, title: clean(row.title, 'projects/invalid-title', 500), status: 'todo' as const, priority: row.priority ?? 'none', tags: [...(row.tags ?? [])], revision: randomUUID(), createdAt: now, updatedAt: now }; }); const activity = this.event(projectId, actor, 'project', template ? `从模板「${template.name}」创建了项目「${project.name}」` : `创建了项目「${project.name}」`); const prefilled = templateItems.length ? this.event(projectId, actor, 'work-item', `模板预填了 ${templateItems.length} 项计划待办`) : undefined; const workItems = Object.fromEntries(templateItems.map(item => [item.id, item])); const next = { ...state, projects: { ...state.projects, [project.id]: project }, configs: { ...state.configs, [config.id]: config }, workItems: { ...state.workItems, ...workItems }, activity: { ...state.activity, [activity.id]: activity, ...(prefilled ? { [prefilled.id]: prefilled } : {}) } }; await this.put(actor,next); return this.snapshot(next,project); }); }
  get(actor: ActorContext, projectId: string) { return this.enqueue(async () => { const state=await this.state(actor); return this.snapshot(state,this.requireProject(state,projectId)); }); }
  archive(actor: ActorContext, projectId: string) { return this.enqueue(async () => { const state=await this.state(actor), current=this.requireProject(state,projectId), project={...current,status:'archived' as const,updatedAt:timestamp()}; await this.put(actor,{...state,projects:{...state.projects,[projectId]:project}}); return project; }); }
  restore(actor: ActorContext, projectId: string) { return this.enqueue(async () => { const state=await this.state(actor), stored=state.projects[projectId]; if(!stored||stored.status!=='archived')throw new Error('projects/not-found'); const current=this.normalizedProject(stored),project={...current,status:'active' as const,updatedAt:timestamp()}; const activity=this.event(projectId,actor,'project',`恢复了项目「${project.name}」`); await this.put(actor,{...state,projects:{...state.projects,[projectId]:project},activity:{...state.activity,[activity.id]:activity}}); return project; }); }
  updateConfig(actor: ActorContext, projectId: string, config: ProjectConfig, expectedRevisionId: string) { return this.enqueue(async () => { const state=await this.state(actor), project=this.requireProject(state,projectId), previous=state.configs[project.configRevisionId]; if (!previous || previous.id !== expectedRevisionId) throw new Error('projects/revision-conflict'); if(estimateProjectInstructionTokens(config.instruction)>PROJECT_INSTRUCTION_TOKEN_BUDGET)throw new Error('projects/instruction-budget-exceeded'); const now=timestamp(), next:ProjectConfigRevision={id:randomUUID(),projectId,number:previous.number+1,instruction:config.instruction,capabilities:[...config.capabilities],createdBy:actor.principalId,createdAt:now}; const activity=this.event(projectId,actor,'project',`更新了项目配置（修订 ${next.number}）`);await this.put(actor,{...state,configs:{...state.configs,[next.id]:next},projects:{...state.projects,[projectId]:{...project,configRevisionId:next.id,updatedAt:now}},activity:{...state.activity,[activity.id]:activity}}); return next; }); }
  addWorkItem(actor: ActorContext, projectId: string, title: string) { return this.enqueue(async()=>{const state=await this.state(actor);this.requireProject(state,projectId);const now=timestamp(),item:ProjectWorkItem={id:randomUUID(),projectId,title:clean(title,'projects/invalid-title',500),status:'todo',priority:'none',tags:[],revision:randomUUID(),createdAt:now,updatedAt:now};const activity=this.event(projectId,actor,'work-item',`新增计划「${item.title}」`);await this.put(actor,{...state,workItems:{...state.workItems,[item.id]:item},activity:{...state.activity,[activity.id]:activity}});return item;});}
  updateWorkItem(actor: ActorContext, projectId: string, patch: Pick<ProjectWorkItem,'id'|'title'|'status'|'assignee'|'priority'|'tags'>, expectedRevision:string) { return this.enqueue(async()=>{const state=await this.state(actor),old=state.workItems[patch.id];if(!old||old.projectId!==projectId)throw new Error('projects/not-found');if(old.revision!==expectedRevision)throw new Error('projects/revision-conflict');const item={...old,...patch,title:clean(patch.title,'projects/invalid-title',500),revision:randomUUID(),updatedAt:timestamp()};const activity=this.event(projectId,actor,'work-item',`更新计划「${item.title}」`);await this.put(actor,{...state,workItems:{...state.workItems,[item.id]:item},activity:{...state.activity,[activity.id]:activity}});return item;});}
  addAsset(actor: ActorContext, projectId:string, input:Omit<ProjectAssetRef,'id'|'projectId'|'createdAt'>){return this.enqueue(async()=>{const state=await this.state(actor);this.requireProject(state,projectId);const existing=Object.values(state.assets).find(row=>row.projectId===projectId&&row.assetId===input.assetId&&row.revisionId===input.revisionId);if(existing)return existing;const ref:ProjectAssetRef={...input,id:randomUUID(),projectId,createdAt:timestamp()};const activity=this.event(projectId,actor,'asset',`关联资产「${ref.name}」`);await this.put(actor,{...state,assets:{...state.assets,[ref.id]:ref},activity:{...state.activity,[activity.id]:activity}});return ref;});}
  removeAsset(actor:ActorContext,projectId:string,refId:string){return this.enqueue(async()=>{const state=await this.state(actor),ref=state.assets[refId];if(!ref||ref.projectId!==projectId)throw new Error('projects/not-found');const assets={...state.assets};delete assets[refId];const activity=this.event(projectId,actor,'asset',`移除资产引用「${ref.name}」`);await this.put(actor,{...state,assets,activity:{...state.activity,[activity.id]:activity}});});}
  validateInputRefs(actor:ActorContext,projectId:string,references:readonly ProjectInputRef[]){return this.enqueue(async()=>{const state=await this.state(actor),project=this.requireProject(state,projectId);return this.validateReferences(state,project,references);});}
  linkTask(actor:ActorContext,projectId:string,sessionId:string,title:string,workItemId?:string,references:readonly ProjectInputRef[]=[],_signal?:AbortSignal,capabilities?:readonly ProjectCapabilityRef[]){return this.enqueue(async()=>{const state=await this.state(actor),project=this.requireProject(state,projectId);if(workItemId&&state.workItems[workItemId]?.projectId!==projectId)throw new Error('projects/not-found');const validated=this.validateReferences(state,project,references);const configured=state.configs[project.configRevisionId].capabilities;const selection=(capabilities??configured).map(ref=>{const bound=configured.find(x=>x.id===ref.id&&x.kind===ref.kind&&x.revision===ref.revision);if(!bound)throw new Error('projects/capability-not-bound');return bound});const link:ProjectTaskLink={id:randomUUID(),projectId,sessionId:clean(sessionId),title:clean(title,'projects/invalid-title',500),configRevisionId:project.configRevisionId,capabilities:selection,...(workItemId?{workItemId}:{}),references:validated,createdAt:timestamp()};const activity=this.event(projectId,actor,'task',`创建任务「${link.title}」`);await this.put(actor,{...state,tasks:{...state.tasks,[link.id]:link},activity:{...state.activity,[activity.id]:activity}});return link;});}
  taskContext(actor:ActorContext,sessionId:string){return this.enqueue(async():Promise<ProjectTaskContext|undefined>=>{const state=await this.state(actor),task=Object.values(state.tasks).find(row=>row.sessionId===sessionId);if(!task)return undefined;const project=state.projects[task.projectId],config=state.configs[task.configRevisionId];if(!project||!config)return undefined;return{availableCapabilities:config.capabilities,project:this.normalizedProject(project),config:{...config,capabilities:task.capabilities??config.capabilities},task:{...task,references:task.references??[]}};});}
  noteDeliveryGap(actor:ActorContext,projectId:string,text:string){return this.enqueue(async()=>{const state=await this.state(actor);this.requireProject(state,projectId);const activity=this.event(projectId,actor,'asset',clean(text,'projects/invalid-title',500));await this.put(actor,{...state,activity:{...state.activity,[activity.id]:activity}});});}

  private listForStatus(actor:ActorContext,query:string,status:Project['status']){return this.enqueue(async()=>{const state=await this.state(actor),needle=query.trim().toLocaleLowerCase();return Object.values(state.projects).map(row=>this.normalizedProject(row)).filter(row=>row.status===status&&(!needle||`${row.name} ${row.description}`.toLocaleLowerCase().includes(needle))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));});}
  private event(projectId:string,actor:ActorContext,kind:ProjectActivity['kind'],text:string):ProjectActivity{return{id:randomUUID(),projectId,kind,text,actorId:actor.principalId,createdAt:timestamp()};}
  private snapshot(state:Stored,project:Project):ProjectSnapshot{const config=state.configs[project.configRevisionId];if(!config)throw new Error('projects/not-found');const filter=<T extends {projectId:string}>(v:Record<string,T>)=>Object.values(v).filter(row=>row.projectId===project.id);return{project:this.normalizedProject(project),config,workItems:filter(state.workItems),assets:filter(state.assets),tasks:filter(state.tasks).map(row=>({...row,references:row.references??[]})),activity:filter(state.activity).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))};}
  private validateReferences(state:Stored,project:Project,references:readonly ProjectInputRef[]){const config=state.configs[project.configRevisionId],unique=new Map<string,ProjectInputRef>();for(const ref of references){const key=`${ref.kind}:${ref.id}`;if(unique.has(key))continue;if(ref.kind==='work-item'){const item=state.workItems[ref.id];if(!item||item.projectId!==project.id||item.revision!==ref.revision)throw new Error('projects/reference-stale');}else if(ref.kind==='asset'){const asset=state.assets[ref.id];if(!asset||asset.projectId!==project.id||asset.revisionId!==ref.revision)throw new Error('projects/reference-stale');}else{const skill=config?.capabilities.find(row=>row.kind==='skill'&&row.id===ref.id);if(!skill||(skill.revision??project.configRevisionId)!==ref.revision)throw new Error('projects/reference-stale');}unique.set(key,{...ref,label:clean(ref.label,'projects/invalid-title',500)});}return[...unique.values()];}
  private normalizedProject(project:Project):Project{return{...project,description:project.description??''};}
  private requireProject(state:Stored,id:string){const row=state.projects[id];if(!row||row.status==='archived')throw new Error('projects/not-found');return this.normalizedProject(row);}
  private async state(actor:ActorContext):Promise<Stored>{const key=projectStateKey(actor.organizationId,actor.principalId),found=await this.states().get(key);if(found)return found as Stored;const state:Stored={schemaVersion:1,projects:{},configs:{},workItems:{},assets:{},tasks:{},activity:{}};await this.states().put(key,state);return state;}
  private put(actor:ActorContext,state:Stored){return this.states().put(projectStateKey(actor.organizationId,actor.principalId),state);}
  private states(){if(!this.table)throw new Error('projects/not-ready');return this.table;}
  private enqueue<T>(work:()=>Promise<T>):Promise<T>{const next=this.serial.then(work,work);this.serial=next.then(()=>undefined,()=>undefined);return next;}
}
