// AUTO-GENERATED by scripts/build-brand-assets.mjs — 请勿手改；改图形请改脚本后重新生成。
//
// 图形基准：用户提供的 ai-media-symbol.svg
//   外层 6 节点（多路媒资）+ 内层 3 节点与折线构成的汇聚内核 + 青绿→青蓝信号渐变。

/** 主标网格边长。 */
export const BRAND_VIEWBOX = 96;

/** 小于该像素尺寸时改用紧凑版（去掉外环、放大内核）。 */
export const BRAND_COMPACT_BELOW = 48;

/** 信号渐变（原始）：青绿 → 青蓝。 */
export const BRAND_GRADIENT = { from: '#13D6AA', to: '#21A8ED' } as const;

/** 信号渐变加深版：浅底小尺寸对比不足时使用。 */
export const BRAND_GRADIENT_DEEP = { from: '#0FA98A', to: '#1B84C4' } as const;

/** 深色底座（应用图标 / 头像）。 */
export const BRAND_TILE_COLOR = '#0B1220';

/** 深色底座圆角与内边距比例（沿用提供方的深底预览比例）。 */
export const BRAND_TILE_RX_RATIO = 0.20833333333333334;
export const BRAND_TILE_INSET_RATIO = 0.125;
export const BRAND_TILE_GLYPH_SCALE = 0.0078125;

export type BrandNode = { readonly cx: number; readonly cy: number; readonly r: number };
export type BrandCut = 'full' | 'compact';

/** 完整版：外环 6 节点。 */
export const BRAND_OUTER_NODES: readonly BrandNode[] = [
  { cx: 48, cy: 10, r: 5 },
  { cx: 78, cy: 29, r: 5 },
  { cx: 78, cy: 67, r: 5 },
  { cx: 48, cy: 86, r: 5 },
  { cx: 18, cy: 67, r: 5 },
  { cx: 18, cy: 29, r: 5 },
];

/** 完整版：内芯折线与 3 节点。 */
export const BRAND_CORE_PATH = 'M37 34 61 48 37 62';
export const BRAND_CORE_STROKE = 7;
export const BRAND_CORE_NODES: readonly BrandNode[] = [
  { cx: 37, cy: 34, r: 8 },
  { cx: 61, cy: 48, r: 8 },
  { cx: 37, cy: 62, r: 8 },
];

/** 紧凑版：内核放大 1.82 倍（坐标已预变换，勿再套 transform，否则渐变被裁）。 */
export const BRAND_COMPACT_CORE_PATH = 'M26.16 22.52 69.84 48 26.16 73.48';
export const BRAND_COMPACT_CORE_STROKE = 12.74;
export const BRAND_COMPACT_CORE_NODES: readonly BrandNode[] = [
  { cx: 26.16, cy: 22.52, r: 14.56 },
  { cx: 69.84, cy: 48, r: 14.56 },
  { cx: 26.16, cy: 73.48, r: 14.56 },
];
