// AUTO-GENERATED by workdsh-web/scripts/sync-brand-to-desktop.mjs — 请勿手改。
//
// 桌面侧品牌名的唯一定义点。Electron 主进程无法在运行时读
// workdsh-web/assets/brand/brand.json（package.json 是静态 JSON，主进程代码会被
// 打包进可执行文件），所以由同步脚本把名字冻成常量。
// 改名：改品牌真源 → 重跑同步；不要手改本文件。

/** 应用显示名：菜单栏、窗口标题、Dock。 */
export const BRAND_DISPLAY_NAME = 'AI融媒中心'

/** 应用英文名：英文安装文案与副标。 */
export const BRAND_DISPLAY_NAME_EN = 'AI Convergence Media Center'
